# The 'check_python' target builds the executable 'check_python' from the source file 'check_python.c'
check_python: check_python.c
    $(CC) $(CFLAGS) -o check_python check_python.c  # Compile 'check_python.c' into the 'check_python' executable using the compiler $(CC) and flags $(CFLAGS)